apiVersion: batch/v1
kind: CronJob
metadata:
  name: mon-cronjob
spec:
  schedule: "*/5 * * * *"
  timeZone: Europe/Paris
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name : mon-conteneur
            image: ubuntu:latest
            command: ["date"]
          restartPolicy: OnFailure